version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: altimetrik
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
